#############################################################################################################################################
# Contains all parameters for the training process
#############################################################################################################################################

#Paths of the train, validation and testing files
Paths:
    train_tfrecord : /no_backups/g009/data/OASIS/tfrecords_data_exp2/training/ 
        #/home/raarmak1/.shashanks/BA_estimation/tfrecords_data/OASIS1_3_combined/tfrecords_data_exp2/training/
        # /home/raarmak1/.shashanks/BA_estimation/tfrecords_data/OASIS1_3_combined/tfrecords_data_cdr0_training/training_cdr0/
        #/home/raarmak1/.shashanks/BA_estimation/tfrecords_data/OASIS1_3_combined/tfrecords_data_exp3/training/
        #/home/raarmak1/.shashanks/BA_estimation/tfrecords_data/OASIS1_3_combined/tfrecords_data_cdr0_training/training_cdr0/

        #/home/raarmak1/.shashanks/BA_estimation/tfrecords_data/OASIS1_3_combined/tfrecords_data_exp3/training/
    #/home/raarmak1/.shashanks/BA_estimation/tfrecords_data/OASIS1_3_combined/tfrecords_data_cdr0_training/training_cdr0/
        #/home/raarmak1/.shashanks/BA_estimation/tfrecords_data/OASIS1_3_combined/tfrecords_data_exp2/training/
#home/raaramk1/.shashanks/BA_estimation/tfrecords_data/training/  #/home/d1308/no_backup/d1308/train_data_brain/ 
    test_tfrecord : /no_backups/g009/data/OASIS/tfrecords_data_exp2/testing/ 
    #/home/raarmak1/.shashanks/BA_estimation/tfrecords_data/OASIS1_3_combined/tfrecords_data_exp2/testing/
    #/home/raarmak1/.shashanks/BA_estimation/tfrecords_data/OASIS1_3_combined/tfrecords_data_cdr0_training/testing_all_cdr/
        
        #/home/raarmak1/.shashanks/BA_estimation/tfrecords_data/OASIS1_3_combined/tfrecords_data_cdr0_training/testing_all_cdr/
    #/home/raarmak1/.shashanks/BA_estimation/tfrecords_data/OASIS1_3_combined/tfrecords_data_cdr0_training/testing_all_cdr/        #
    #/home/raarmak1/.shashanks/BA_estimation/tfrecords_data/OASIS1_3_combined/tfrecords_data_exp2/testing/ #/home/raaramk1/.shashanks/BA_estimation/tfrecords_data/testing/ #/home/d1308/no_backup/d1308/test_data_brain/ 
    labels : /no_backups/g009/data/oasis1_oasis3_labels.csv
    #/home/raarmak1/.shashanks/BA_estimation/csv_data/OASIS1_3_combined/oasis1_oasis3_labels.csv 

    unhealthy : /no_backups/g009/data/OASIS/tfrecords_data_exp2/bio_unhealthy_data/ 
#/home/raarmak1/.shashanks/BA_estimation/tfrecords_data/OASIS1_3_combined/bio_unhealthy_data/

Data:
    train_val_split : 0.82                        # e.g. 0.8 -> 80% train, 20% validation

Pretrained_Model:
    # weights of a pretrained network
    path : /usrhomes/g009/shashanks/Master_Thesis_BA_DeepVis/BA_estimation/Final_Codes/Brain_BiologicalAge_Estimation/exp/exp2.2/model/age_net_oasis1_3.hdf5 
#'/home/raarmak1/.shashanks/BA_estimation/Final_Codes/Brain_BiologicalAge_Estimation/exp/exp2/model/age_net_oasis1_3.hdf5' 

Training:
    batch_size : 16 #4
    samples : 20 # No of volume chunks
    image_shape: [121, 145, 6] # for mean slices  #[121, 145, 6]   #Image shape to be fed into the model
    gpu_num : 2
    background_process : True
    num_epochs : 250
    learning_rate: 0.0000062
    num_parallel_calls: 4
    numgpus: 1

Case:  'train' #'vis' #'test' #'train'
#can be 'train', 'test
