#############################################################################################################################################
# Contains all parameters for the training process
#############################################################################################################################################

#Paths of the train, validation and testing files
Paths:
    train_tfrecord : /no_backups/g009/data/OASIS/tfrecords_data_exp2/training/

    test_tfrecord : /no_backups/g009/data/OASIS/tfrecords_data_exp2/testing/

 
    labels : /no_backups/g009/data/oasis1_oasis3_labels.csv

Data:
    train_val_split : 0.82                        # e.g. 0.8 -> 80% train, 20% validation

Pretrained_Model:
    # weights of a pretrained network
    path : /usrhomes/g009/shashanks/Master_Thesis_BA_DeepVis/BA_estimation/Final_Codes/Brain_BiologicalAge_Estimation/exp/exp2.1/model/age_net_oasis1_3.hdf5
#'/home/raarmak1/.shashanks/BA_estimation/Final_Codes/Brain_ChronologicalAge_Estimation/exp/exp2/model/age_net_oasis1_3.hdf5' 

Training:
    batch_size : 8 #4
    samples : 20 # No of volume chunks
    image_shape: [121, 145, 6] # for mean slices  #[121, 145, 6]   #Image shape to be fed into the model
    gpu_num : 2
    background_process : True
    num_epochs : 250 #200 #250
    learning_rate: 0.0000062
    num_parallel_calls: 4
    numgpus: 1

Case:  'train' #'vis' #'test' #'train'
#can be 'train', 'test
